#!/usr/bin/env python3
"""Emit a C++20 module interface that imports std and fmt.

The generated code is beside the point; what the demo exercises is that meson
knows nothing about this file at setup time beyond its output name. The build
runs the generator, then the P1689 scan finds `export module <name>;` plus the
`import std;` / `import fmt;` edges and orders the compiles accordingly.
"""

import argparse
from pathlib import Path

TEMPLATE = '''\
// Generated by tools/gen-module.py -- do not edit.

export module {module};

import std;
import fmt;

export namespace {module} {{

std::string greet(std::string_view who) {{
  return fmt::format("{greeting}, {{}}!", who);
}}

std::vector<std::string> roster() {{
  auto names = std::vector<std::string_view>{{{names}}};
  auto out = std::vector<std::string>{{}};
  for (std::size_t i = 0; i < names.size(); ++i) {{
    out.push_back(fmt::format("{{}}. {{}}", i + 1, greet(names[i])));
  }}
  return out;
}}

}}  // namespace {module}
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--module', required=True,
                        help='name of the module to export (also the namespace)')
    parser.add_argument('--greeting', default='Hello',
                        help='greeting the generated code formats with fmt')
    parser.add_argument('--output', required=True, type=Path,
                        help='module interface file to write')
    parser.add_argument('names', nargs='+',
                        help='names the generated roster() greets')
    args = parser.parse_args()

    names = ', '.join(f'"{name}"' for name in args.names)
    args.output.write_text(TEMPLATE.format(module=args.module,
                                           greeting=args.greeting,
                                           names=names))


if __name__ == '__main__':
    main()
